### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by er2de2** [ltheinrich/etopa#192]
Can you make docker image for Etopa server?

**Comment by ltheinrich** [comment]
Thanks for the suggestion.

I have created a [Docker image](https://github.com/ltheinrich/etopa?tab=readme-ov-file#docker) for the Etopa server (backend + web frontend): d7bbe12b15d706f6edc918f86aa26aad400f53ec
Feedback would be very much appreciated, if you have some experience with Docker images :)

**Comment by er2de2** [comment]
Everything works great...config is simple.....i deploy my etopa server on vps, create user, import database from my account on etopa.de....perfecto:). Thank You very much.
