### ISSUE TITLE
Own docker image

### ISSUE THREAD

**Issue by er2de2** [ltheinrich/etopa#194]
Hello.
I would like to create my own docker image.
Could you write a short tutorial in the readme?

**Comment by ltheinrich** [comment]
The current Docker image is very similar to the installation described in the wiki: https://github.com/ltheinrich/etopa/wiki/Install-server
It basically just creates an image with nginx and the Etopa binary, which it both starts. However, the [nginx configuration](https://github.com/ltheinrich/etopa/blob/master/docker/nginx.conf) is important so serve the web app and backend on the same domain. You can review the other Docker files here:
https://github.com/ltheinrich/etopa/tree/master/docker
https://github.com/ltheinrich/etopa/blob/master/Dockerfile

You could copy these files/configurations and start with that.
